Make veloren server services instantiable, add socket

diff --git a/assets/veloren-server/update_veloren_server b/assets/veloren-server/update_veloren_server
--- a/assets/veloren-server/update_veloren_server
+++ b/assets/veloren-server/update_veloren_server
@@ -1,42 +1,50 @@
 #!/bin/bash
 
-REMOTE_VER="$(curl -s 'https://download.veloren.net/version/linux/aarch64/nightly')"
-REMOTE_DIR="/usr/veloren"
-FORCE_UPDATE="false"
-FILENAME="veloren-aarch64"
-
-mkdir -p $REMOTE_DIR
-
-while test "$#" -gt 0; do
-  case "$1" in
-   -f|--force) 
+while getopts ":f:t:" opt; do
+    case $opt in
+    f)
         FORCE_UPDATE="true"
-        shift
         ;;
-    *)
-        break
+    t)
+        TARGET_SERVER="$OPTARG"
         ;;
-  esac
+    \?)
+        echo "Invalid option -$OPTARG" >&2
+        exit 1
+        ;;
+    esac
+
+    case $OPTARG in
+    -*)
+        echo "Option $opt needs a valid argument"
+        exit 1
+        ;;
+    esac
 done
 
-if [[ $REMOTE_VER = "$(cat $REMOTE_DIR/version)" && $FORCE_UPDATE == "false" ]]; then
+REMOTE_VER="$(curl -s 'https://download.veloren.net/version/linux/aarch64/nightly')"
+SERVER_DIR="/srv/veloren/${TARGET_SERVER:-"production"}"
+FORCE_UPDATE="false"
+FILENAME="veloren-aarch64"
+CURRENT_VER=$(cat "$SERVER_DIR"/version 2>&-)
+
+mkdir -p "$SERVER_DIR"
+
+if [[ $REMOTE_VER == $CURRENT_VER && $FORCE_UPDATE == "false" ]]; then
     echo -e "\e[32m\e[1mYour server is up-to-date :)\e[0m"
 else
-    echo $REMOTE_VER > $REMOTE_DIR/version
+    echo "$REMOTE_VER" >"$SERVER_DIR"/version
 
-    (cd $REMOTE_DIR && curl -L -o $FILENAME --connect-timeout 30 \
-        --max-time 30 \
+    (cd "$SERVER_DIR" && curl -L -o $FILENAME --connect-timeout 300 \
+        --max-time 300 \
         --retry 300 \
         --retry-delay 5 \
-        'https://download.veloren.net/latest/linux/aarch64/nightly')
+        'https://download.veloren.net/latest/linux/x86_64/nightly')
 
-    (cd $REMOTE_DIR && unzip -qo $FILENAME)
-    (cd $REMOTE_DIR && rm -rf $FILENAME)
+    (cd "$SERVER_DIR" && unzip -qo $FILENAME)
+    (cd "$SERVER_DIR" && rm -rf $FILENAME)
 
-    systemctl restart veloren-server.service
+    systemctl restart veloren@.service
 
     echo -e "\e[32m\e[1mSuccessfully updated server to latest version ($REMOTE_VER)\e[0m"
 fi
-
-
-
